apiVersion: v1
data:
  prometheus.yml: |
    global:
      evaluation_interval: 5s
      scrape_interval: 5s
      scrape_timeout: 5s
    scrape_configs:
    - job_name: 'sriov-metrics'
      scheme: http
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: ^(.*):\d+$
        target_label: __address__
        replacement: $1:9999
      - target_label: __scheme__
        replacement: http
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: prometheus
    component: server
  name: minimum-scrape-config-sriov-exporter.yml 
  namespace: monitoring
